[project]
name = "prospectorMahery"
r_version = "4.5"

# A list of repositories to fetch packages from. Order matters: we will try to get a package from each repository in order.
# The alias is only used in this file if you want to specifically require a dependency to come from a certain repository.
# Example: { alias = "PPM", url = "https://packagemanager.posit.co/cran/latest" },
repositories = [
    { alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest" },
]

# A list of packages to install and any additional configuration
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN"},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
dependencies = [
    "dplyr",
    "languageserver",
    "httpgd",
    "usethis",
    "here",
    "rmarkdown",
    { name = "bakepipe", git = "https://github.com/vangberg/bakepipe", branch = "main" },
    "fusen",
    "remotes",
    "fledge",
    "readr",
    "stringr",
    "withr",
    "readxl",
    "skimr",
    { name = "prospectorMahery", path = ".", dependencies_only = true },
    "httpuv",
    "tidyverse",
    "websocket",
    "targets",
    { name = "tarchetypes", git = "https://github.com/ropensci/tarchetypes/", branch = "main" },
    "parsermd",
    "codetools",
    "quarto",
    "rlang",
    "purrr",
    "tibble",
    "devtools",
]
