---
title: "flat_cleaning_functions.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# Cleaning Functions

We are defining in a handful of cleaning functions that
came with the project below.


# fix_recoded
    
```{r development-fix_recoded}
# You can prepare the code of the fix_recoded() function here
```
  
```{r function-fix_recoded}
#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
fix_recoded <- function(diet_df) {
  diet_df <- diet_df %>%
    dplyr::mutate(FoodName_Recoded = case_when(
      FoodName_Recoded == "18 petit beer" ~ "petit beurre",                                                                                                                                                                                          
      FoodName_Recoded %in% c("abazaha", "manioc sec") ~ "ambazaha",    
      FoodName_Recoded == "ankanga dy" ~ "akanga",
      FoodName_Recoded == "alleta" ~ "alaita",
      FoodName_Recoded == "agarigadiny" ~ "voangaragaradiny",     
      FoodName_Recoded %in% c("agnamalao", "agnanmalo, agnantsenko",
                              "anamalao, agnantsindra", "anamalao, hafa",
                              "agnanmalo&-&agnantsenko", "anamalao, agnantsenko",
                              "vogno anamalao", "anamalahy") ~ "anamalao",
      FoodName_Recoded == "agnansahogno" ~ "agnantsahogno",
      FoodName_Recoded == "agnantsindra" ~ "anantsindra",
      FoodName_Recoded %in% c("agnantsenko", "agnantseko, agnantsirebika") ~ "agnantseko",
      FoodName_Recoded %in% c("ainan'aomby (vokany)", "viande de boeuf") ~ "henanomby", 
      FoodName_Recoded %in% c("akoho vositry", "lampirana") ~ "akoho vohitry",
      FoodName_Recoded == "amalombandana" ~ "amalona",
      FoodName_Recoded == "ambany vihy fotsy miharo tsikatsakatsa sy alava" ~ "ambanivihy",  
      FoodName_Recoded == "ambaribadefo" ~ "ambarabadefo",
      FoodName_Recoded == "ambarababoaka" ~ "fontsy ambarababoaka",  
      FoodName_Recoded %in% c("ambazaha manta", "manioc frais") ~ "ambazaha",
      FoodName_Recoded == "amilobe" ~ "rhum",    
      FoodName_Recoded == "apalibe" ~ "ampalibe",
      FoodName_Recoded == "ampiny fisaka leany" ~ "ampiny fisaka leny",
      FoodName_Recoded == "ampiny natono" ~ "ampiny",
      FoodName_Recoded %in% c("ampilimosy", "ampilime") ~ "pamplemousse",
      FoodName_Recoded == "ananas" ~ "manasy",
      FoodName_Recoded == "anamamy" ~ "agnamamy",
      FoodName_Recoded == "anambe" ~ "agnambe",
      FoodName_Recoded == "anampandrony" ~ "agnampandrony",
      FoodName_Recoded == "anandrano" ~ "anantsalady",
      FoodName_Recoded == "anankorana" ~ "anakorana",
      FoodName_Recoded == "anantarika" ~ "agnantarika",
      FoodName_Recoded == "anangisa" ~ "agnangisa",
      FoodName_Recoded == "anantsahono" ~ "agnantsahogno",
      FoodName_Recoded == "anantsenko" ~ "agnantseko",
      FoodName_Recoded == "anatsinahy" ~ "anantsinahy",
      FoodName_Recoded == "anatsonga" ~ "anantsonga",
      FoodName_Recoded %in% c("anantsirebika", "ravimboatavo") ~ "agnantsirebika",
      FoodName_Recoded %in% c("anatsiriry tokony", "anantsiriry") ~ "agnantsiriry",
      FoodName_Recoded %in% c("anantsomanga", "ravimbomanga na ravimbele") ~ "agnantsomanga",
      FoodName_Recoded == "antsity" ~ "asity",                                                                                                                                                                                                       
      FoodName_Recoded == "antsoza" ~ "antsaora", 
      FoodName_Recoded %in% c("apollo", "apolo", "appollo", "appolo", "pate umy", 
                              "pati sec", "paty matsiro") ~ "pate apollo",
      FoodName_Recoded %in% c("atody drakidraky", "atody dokitra") ~ "atody vorona",
      FoodName_Recoded %in% c("atody", "oeuf") ~ "atody akoho", 
      FoodName_Recoded %in% c("baigne", "baignet", "beignet") ~ "beignets",
      FoodName_Recoded == "balainy natono" ~ "balainy", 
      FoodName_Recoded %in% c("bagniagna", "bagniana", "baniana", "bagniany", 
                              "babagniana") ~ "tohy",
      FoodName_Recoded %in% c("bantaka", "bolaity") ~ "mofo bontaka",                                                                                                                                                                                                
      FoodName_Recoded == "berioce" ~ "mofo biriosy",                                                                                                                                                                                                
      FoodName_Recoded == "beurre (sotro)" ~ "beurre",                                                                                                                                                                                               
      FoodName_Recoded %in% c("bitavia masaka", "banane", "fatsimasaka bitavia",
                              "fontsy bitavia manta") ~ "fontsy bitavia",                                                                                                                                                                                       
      FoodName_Recoded == "boatis" ~ "ronono boite",                                                                                                                                                                                                 
      FoodName_Recoded == "bombom sofile" ~ "bonbon souffle", 
      FoodName_Recoded == "biankera " ~ "biankera",
      FoodName_Recoded == "belapotrika anana" ~ "belapotrika",
      FoodName_Recoded == "betanihazo haricot" ~ "betanihazo",
      FoodName_Recoded %in% c("buscuit", "yami", "biscuit glucosse") ~ "biscuit",
      FoodName_Recoded == "maya" ~ "boity (maya)",
      FoodName_Recoded == "boezarana" ~ "boezarano",
      FoodName_Recoded == "caca pigeon" ~ "caca pigeon",   
      FoodName_Recoded == "canne a sucre" ~ "fary",
      FoodName_Recoded == "carotte" ~ "karaoty",
      FoodName_Recoded == "cedapy" ~ "sedaap",       
      FoodName_Recoded == "chouchoute" ~ "sosoty",
      FoodName_Recoded == "classico" ~ "coca cola",      
      FoodName_Recoded %in% c("coffee", "kafe") ~ "café",
      FoodName_Recoded == "corosol" ~ "corossol",   
      FoodName_Recoded == "crevette maina ranomasina" ~ "orana maina",
      FoodName_Recoded == "crevette lena ranomasina" ~ "orana legny",
      FoodName_Recoded == "cucumbre" ~ "concombre", 
      FoodName_Recoded == "cucumber" ~ "concombre",
      FoodName_Recoded == "kakao" ~ "cacao",
      FoodName_Recoded == "kiresaoly" ~ "corossol",
      FoodName_Recoded %in% c("dimohiny", "domohina", "domohina ", "domohiny", 
                              "domony") ~ "domoina",
      FoodName_Recoded == "dimohina (vokany)" ~ "domoina",                                                                                                                                                                                           
      FoodName_Recoded == "dinamiky" ~ "dynamic",                                                                                                                                                                                                    
      FoodName_Recoded == "dipin" ~ "mofo du pain",                                                                                                                                                                                                  
      FoodName_Recoded == "divin" ~ "du vin",     
      FoodName_Recoded == "enalaza" ~ "henalaza",
      FoodName_Recoded == "la farina" ~ "farine",
      FoodName_Recoded == "falakana sahogno tokony" ~ "falakana sahogno",
      FoodName_Recoded == "fasaka" ~ "lagnorampisaka",
      FoodName_Recoded == "fena" ~ "fay",
      FoodName_Recoded == "fantsimasaka  handatra" ~ "fontsy andatra",                                                                                                                                                                               
      FoodName_Recoded == "fantsy  malamaravina" ~ "fontsy malamaravina",                                                                                                                                                                            
      FoodName_Recoded == "farilac (sotro)" ~ "farilac",                                                                                                                                                                                             
      FoodName_Recoded %in% c("felany", "felany madinika", "hesikesika", 
                              "hesikesika2f", "felana", "felagna") ~ "felany hesikesiky",
      FoodName_Recoded %in% c("faoza zalimaty natao frite(kinkony)", 
                              "faoza zalimety frite") ~ "foza",
      FoodName_Recoded == "fiamandy" ~ "fiamandry",
      FoodName_Recoded == "fiambazana + trovoko" ~ "fiambazana",
      FoodName_Recoded == "fiana " ~ "fiana",
      FoodName_Recoded == "fiantandroko" ~ "fiantandroka",
      FoodName_Recoded == "finego" ~ "finengo",
      FoodName_Recoded == "firasa(natono)" ~ "firasa",                                                                                                                                                                                               
      FoodName_Recoded == "firity ndaoko" ~ "frite laoko",                                                                                                                                                                                           
      FoodName_Recoded == "fontsy falo fanahy masaka" ~ "fontsy valofanahy",                                                                                                                                                                         
      FoodName_Recoded == "fontsy miharo vary" ~ "vary sy fontsy",                                                                                                                                                                                   
      FoodName_Recoded == "fontsy manta bitavia" ~ "fontsy manta",
      FoodName_Recoded == "fontsy malamaravina manta" ~ "fontsy malamaravina",
      FoodName_Recoded == "fontsy mamimamy" ~ "fontsy masaka",
      FoodName_Recoded == "fontsy masaka andatra" ~ "fontsy andatra",
      FoodName_Recoded == "fosa/jaboady/vontsira" ~ "jaboady",
      FoodName_Recoded == "frasa" ~ "firasa",
      FoodName_Recoded == "fresy" ~ "fresh",                                                                                                                                                                                                         
      FoodName_Recoded == "fromage la vache qui rit" ~ "vache qui rit",
      FoodName_Recoded == "galette" ~ "biscuit",
      FoodName_Recoded %in% c("gava say masaka", "goyave") ~ "gavobe",                                                                                                                                                                                              
      FoodName_Recoded == "gavo  mbazaha" ~ "gavo sinoa",                                                                                                                                                                                            
      FoodName_Recoded %in% c("granadaily", "grenadelle") ~ "grenadille", 
      FoodName_Recoded == "goty" ~ "biscuit",
      FoodName_Recoded == "jano" ~ "zano",
      FoodName_Recoded == "hainalaza" ~ "henalaza",
      FoodName_Recoded %in% c("honey", "miel") ~ "antely", 
      FoodName_Recoded == "hovibe" ~ "ovy be",  
      FoodName_Recoded == "ima" ~ "hima",
      FoodName_Recoded %in% c("hovotra ampalime", "hovotra ampalimier") ~ "hovotra palmier",
      FoodName_Recoded == "hovondravina" ~ "hovotra ravina",
      FoodName_Recoded == "hovotra mafaiky hely" ~ "hovotra boresy",
      FoodName_Recoded %in% c("kaikaimavo", "kaikimavo") ~ "kainkaimavo/tsaintsaimavo",
      FoodName_Recoded == "tsaitsaimpotsy" ~ "kaikaimpotsy, tsaintsaimpotsy, tsentsempotsy",
      FoodName_Recoded == "huiles" ~ "menaka",
      FoodName_Recoded == "jamblon" ~ "jambon",                                                                                                                                                                                                      
      FoodName_Recoded == "jano" ~ "zano",                                                                                                                                                                                                           
      FoodName_Recoded == "jebojebo natono" ~ "jebojebo",                                                                                                                                                                                            
      FoodName_Recoded == "jifo" ~ "mofo jofo",                                                                                                                                                                                                      
      FoodName_Recoded == "jus cola kopy" ~ "jus cola",                                                                                                                                                                                              
      FoodName_Recoded == "jus manasy vera" ~ "jus manasy",
      FoodName_Recoded == "kaotrana" ~ "kaotrany",
      FoodName_Recoded == "kasaira" ~ "kasera",
      FoodName_Recoded == "casera" ~ "kasera",
      FoodName_Recoded %in% c("kabaro maina", "kabaro lena") ~ "gros pois",
      FoodName_Recoded == "karombaola" ~ "karombola",                                                                                                                                                                                                
      FoodName_Recoded == "kilandy natono" ~ "kilandy",                                                                                                                                                                                              
      FoodName_Recoded == "koba fontsy (sotro)" ~ "koba",                                                                                                                                                                                            
      FoodName_Recoded == "kraky" ~ "cracky", 
      FoodName_Recoded == "koha" ~ "koa",
      FoodName_Recoded == "kotragna" ~ "kisaka",
      FoodName_Recoded == "cafau" ~ "lagnaorana",
      FoodName_Recoded == "bitay" ~ "betay",
      FoodName_Recoded == "lagnoramahintina" ~ "lagnaorana",
      FoodName_Recoded == "leny" ~ "laoko",
      FoodName_Recoded %in% c("andranomamy maigny", "trondro maina ranomamy") ~ "laoko ranomamy maina",
      FoodName_Recoded %in% c("maigny", "andranomasina maigny", 
                              "trondro maina ranomasina") ~ "laoko ranomasina maina",
      FoodName_Recoded %in% c("andranomamy leny", "legny andranomamy", 
                              "trondro lena ranomamy") ~ "laoko ranomamy legny",
      FoodName_Recoded == "la farina" ~ "farine",                                                                                                                                                                                                    
      FoodName_Recoded == "laindronga" ~ "drongo", 
      FoodName_Recoded == "lagnoramena" ~ "lagnaoramena",
      FoodName_Recoded == "lambdodia" ~ "lambo dia",
      FoodName_Recoded == "langorana" ~ "lagnorana",
      FoodName_Recoded == "laohany so" ~ "soy",                                                                                                                                                                                                      
      FoodName_Recoded == "laoko   maingy   fiantandroko" ~ "fiantandroka",
      FoodName_Recoded == "laoko atono andranofalafa" ~ "tsaingatsainga",
      FoodName_Recoded == "laoko maigny salelo(izy maigny)" ~ "salelo",                                                                                                                                                                              
      FoodName_Recoded %in% c("laoko natono", "trondro lena ranomasina", 
                              "andranomasina") ~ "laoko ranomasina legny",                                                                                                                                                                                 
      FoodName_Recoded == "laoko natono (tsaingatsainga)" ~ "tsaingatsainga",                                                                                                                                                                        
      FoodName_Recoded == "laoko sira" ~ "laoko sira", 
      FoodName_Recoded == "lasary (sotro)" ~ "lasary vapaza",                                                                                                                                                                                        
      FoodName_Recoded == "lasary cocombre" ~ "lasary concombre",                                                                                                                                                                                    
      FoodName_Recoded == "lava" ~ "lafa",                                                                                                                                                                                                           
      FoodName_Recoded == "lava bitay natono" ~ "lafa bitay",                                                                                                                                                                                        
      FoodName_Recoded == "lekisintsinoa" ~ "letchy chinoa",      
      FoodName_Recoded == "lentilles" ~ "tsiasisa",
      FoodName_Recoded == "licchini" ~ "lucchini",                                                                                                                                                                                                   
      FoodName_Recoded == "lion chicken (senyorita)" ~ "jumbo",
      FoodName_Recoded == "litchee sinoa" ~ "letchy chinoa",
      FoodName_Recoded == "limonade" ~ "bonbon anglais",
      FoodName_Recoded == "longo fy" ~ "lucchini",                                                                                                                                                                                                   
      FoodName_Recoded %in% c("lychee", "litchis") ~ "letchi",                                                                                                                                                                                                       
      FoodName_Recoded %in% c("madakemboka", "pains") ~ "mofo",                                                                                                                                                                                                    
      FoodName_Recoded == "manavy aliny natono" ~ "manavy",  
      FoodName_Recoded %in% c("mangambazaha", "manga vasirindry", "mangue") ~ "manga",
      FoodName_Recoded %in% c("mankafy", "miamy") ~ "jumbo",
      FoodName_Recoded == "maria" ~ "mariha",
      FoodName_Recoded == "mavon" ~ "mavondro",
      FoodName_Recoded %in% c("maritaigny", "marotaigny") ~ "martin",
      FoodName_Recoded == "menaheliky" ~ "menahelika",
      FoodName_Recoded == "mister boom" ~ "siligum",                                                                                                                                                                                                 
      FoodName_Recoded == "mofo   ambazaha" ~ "mofo ambazaha",                                                                                                                                                                                       
      FoodName_Recoded == "mofo   ravina" ~ "mofo ravina",     
      FoodName_Recoded == "mofo dipin" ~ "mofo du pain",
      FoodName_Recoded == "moforavina" ~ "mofo ravina",
      FoodName_Recoded == "orange" ~ "voahangy",
      FoodName_Recoded %in% c("ovy", "oviala", "ovi be") ~ "ovy be",
      FoodName_Recoded %in% c("ovy ala", "ovidy") ~ "ovy dia",
      FoodName_Recoded == "patate douce" ~ "tsomanga",
      FoodName_Recoded == "patsaoly" ~ "patrola",
      FoodName_Recoded %in% c("paomy", "pomme") ~ "paoma",                                                                                                                                                                                                         
      FoodName_Recoded == "pepermint" ~ "peppermint",   
      FoodName_Recoded == "petits pois frais" ~ "lojo",
      FoodName_Recoded %in% c("pisitasy", "arachides sechees") ~ "pistaches",                                                                                                                                                                                                  
      FoodName_Recoded == "pop drik (vera)" ~ "sirop",                                                                                                                                                                                               
      FoodName_Recoded == "queens" ~ "labiera",       
      FoodName_Recoded %in% c("ramboho", "rambohy", "ramboly") ~ "rambolo",
      FoodName_Recoded == "raonjy" ~ "voahangy",
      FoodName_Recoded == "ravina hetsika" ~ "ravina hesikesika",
      FoodName_Recoded == "ranompary" ~ "ranopary",
      FoodName_Recoded == "ranombany" ~ "vanio sijiavo",                                                                                                                                                                                             
      FoodName_Recoded %in% c("ravigny", "ravitoto") ~ "ravinambazaha",                                                                                                                                                                                               
      FoodName_Recoded == "ravina angarigadiny" ~ "voangaragaradiny",   
      FoodName_Recoded == "ravitsosety" ~ "ravina tsosoty",
      FoodName_Recoded %in% c("ronono omby", "ronono aomby", "lait") ~ "ronono", 
      FoodName_Recoded %in% c("boi", "boity ( socolait)", "boity (maya)",
                              "boity (ronono mandry mamy)socolait", 
                              "boity (tople)", "boity maventy", 
                              "boity(socolait)", "dyanas", "mamy mandry", 
                              "podra", "poudre", "ronoboit", "socolait", 
                              "tsard", "wiam") ~ "ronono boite",
      FoodName_Recoded == "sadoko" ~ "vorondrano",                                                                                                                                                                                                   
      FoodName_Recoded == "sahoaba" ~ "sahoaba ambazaha",                                                                                                                                                                                            
      FoodName_Recoded == "sahoaba  ovy  be" ~ "sahoaba ovibe",                                                                                                                                                                                      
      FoodName_Recoded == "sahoaba  tsakotsako" ~ "sahoaba tsakotsako",                                                                                                                                                                              
      FoodName_Recoded == "sahoaba sonambo" ~ "sahoaba sognambo",                                                                                                                                                                                    
      FoodName_Recoded == "sahoaba bontsy bitavia  miharo sahogno" ~ "sahoaba fontsy",                                                                                                                                                               
      FoodName_Recoded == "sahoaba sahogno" ~ "sahoaba sahogno",                                                                                                                                                                                     
      FoodName_Recoded == "sahoaba varifemba" ~ "sosoa",                                                                                                                                                                                             
      FoodName_Recoded == "sahognambo" ~ "sognambo",     
      FoodName_Recoded %in% c("sahogno mandady", "sahognompotsy", "saonjo / taro") ~ "sahogno",
      FoodName_Recoded %in% c("sakaitany", "gingembre") ~ "sakay tany",                                                                                                                                                                                                
      FoodName_Recoded %in% c("sakay birereho", "sakay be", "piment") ~ "sakay",                                                                                                                                                                                                
      FoodName_Recoded == "samaosa" ~ "samboso",                                                                                                                                                                                                     
      FoodName_Recoded %in% c("savoka", "avocat") ~ "zavoka",     
      FoodName_Recoded == "saokiny" ~ "sakoana",
      FoodName_Recoded %in% c("sosy tomaty", "tomate boite", "saosy tomate") ~ "sauce tomate",
      FoodName_Recoded == "saoja" ~ "soja",
      FoodName_Recoded == "salailalaila" ~ "salelalela",
      FoodName_Recoded == "satraky" ~ "salavatraka",
      FoodName_Recoded %in% c("sabireniny", "sambireny") ~ "sambireniny",
      FoodName_Recoded %in% c("pate seddap", "sedap", "sedapy") ~ "sedaap",
      FoodName_Recoded == "sijabombany" ~ "vanio sijiavo",
      FoodName_Recoded == "sifotra" ~ "sifodava",
      FoodName_Recoded == "sira" ~ "sira",                                                                                                                                                                                                           
      FoodName_Recoded == "sorindra firiry" ~ "sorindra",
      FoodName_Recoded == "sokiny" ~ "sokina",
      FoodName_Recoded == "sorikay" ~ "sorokay",
      FoodName_Recoded %in% c("sognambo mamimamy", "sognambo jaira", 
                              "soanambo") ~ "sognambo", 
      FoodName_Recoded == "sucre" ~ "siramamy",
      FoodName_Recoded == "talandohavato" ~ "ambatovazana",
      FoodName_Recoded == "tamarin" ~ "madiro",
      FoodName_Recoded %in% c("telofehiny", "telo fehy") ~ "telofehy",
      FoodName_Recoded %in% c("thon salady", "tohontsalady", "tohonamboalava") ~ "tohonandrongo",
      FoodName_Recoded == "tilapia natono" ~ "tilapia",                                                                                                                                                                                              
      FoodName_Recoded == "tomaty" ~ "tomate",                                                                                                                                                                                                       
      FoodName_Recoded %in% c("tongobe", "oignon") ~ "tongolo",                                                                                                                                                                                                     
      FoodName_Recoded == "tovy madamo maigny" ~ "tovo",                                                                                                                                                                                             
      FoodName_Recoded == "tritrikala" ~ "tritriala",     
      FoodName_Recoded %in% c("tradraka", "trandraka/sokina") ~ "trandraka",
      FoodName_Recoded == "tritrikiala" ~ "tritriala",
      FoodName_Recoded == "tsaingantsainga" ~ "tsaingatsainga",
      FoodName_Recoded == "tsakotsako" ~ "tsakotsako legny",
      FoodName_Recoded == "tsikoza" ~ "tsikaoza",
      FoodName_Recoded %in% c("tsikoraivana", "tsokoreva", "tokorevana") ~ "tsikorevana",
      FoodName_Recoded %in% c("daboira", "tsirebika/daboara", "courge") ~ "tsirebika",
      FoodName_Recoded == "tsiasisa 2 kp haricot 2kp" ~ "tsiasisa",
      FoodName_Recoded == "tsiasisa haricot" ~ "tsiasisa",
      FoodName_Recoded == "tsidimy mahintiny" ~ "tsidimy",
      FoodName_Recoded %in% c("haricot, tsiasisa, voantsorako", "haricot sec", 
                              "haricot blanc frais", "haricot frais") ~ "haricot",
      FoodName_Recoded == "tamantesy" ~ "tomate",
      FoodName_Recoded == "ton" ~ "thon",
      FoodName_Recoded == "tongolo be" ~ "tongolo",
      FoodName_Recoded == "tongolo filo" ~ "tongolo raviny",
      FoodName_Recoded %in% c("tongolo lay", "ail") ~ "tongolay",
      FoodName_Recoded == "tohy " ~ "tohy",
      FoodName_Recoded == "torovoko" ~ "torovoka", 
      FoodName_Recoded == "tovy (kp)" ~ "tovo",
      FoodName_Recoded == "tritrikiala" ~ "tritriala",
      FoodName_Recoded == "trovoko" ~ "torovoka",
      FoodName_Recoded == "vangabe" ~ "vanga",                                                                                                                                                                                                       
      FoodName_Recoded %in% c("vanimagny", "vany maigny", "coco") ~ "voanio",
      FoodName_Recoded %in% c("vary masaka", "riz", "vary maina") ~ "vary",
      FoodName_Recoded %in% c("vatsikokiky", "vatsokopiky", "vantsikopiky", 
                              "voantsikobika", "vatsikobiky") ~ "voatsikopoka",
      FoodName_Recoded %in% c("voanemba", "vontaka") ~ "autres fruits",
      FoodName_Recoded == "vaongy  dy" ~ "voahangy dy",                                                                                                                                                                                              
      FoodName_Recoded %in% c("vapaza", "papaye") ~ "vapaza masaka",                                                                                                                                                                                                
      FoodName_Recoded == "varanto" ~ "varanto",                                                                                                                                                                                                     
      FoodName_Recoded == "varotro" ~ "varotro",                                                                                                                                                                                                     
      FoodName_Recoded == "vaseva" ~ "vaseva",                                                                                                                                                                                                       
      FoodName_Recoded == "vasihy" ~ "voasirindrina",  
      FoodName_Recoded == "viande de porc" ~ "henandambo",
      FoodName_Recoded == "voalela" ~ "voampandela",                                                                                                                                                                                                     
      FoodName_Recoded %in% c("voangy   mandariny", "madanrine") ~ "mandarina",                                                                                                                                                                                        
      FoodName_Recoded %in% c("voangy tsaoha", "citron") ~ "voahangy tsaoha",
      FoodName_Recoded == "voangar" ~ "voangaragaradiny",
      FoodName_Recoded %in% c("voemba", "sorgho") ~ "vohaimba",
      FoodName_Recoded == "voany lingaoza" ~ "lingoza",                                                                                                                                                                                              
      FoodName_Recoded == "vondrafia" ~ "voandrafia",
      FoodName_Recoded %in% c("voanjobory lena", "voanjobory maina") ~ "voanjobory",
      FoodName_Recoded == "vogno" ~ "vaogno",
      FoodName_Recoded == "vorintsiloza" ~ "kolokoloko",
      FoodName_Recoded %in% c("gidro", "varika") ~ "varikosy",
      FoodName_Recoded %in% c("drakidraky", "sadoko") ~"vorondrano",
      FoodName_Recoded == "yaourt" ~ "yaourt",                                                                                                                                                                                                       
      FoodName_Recoded == "zambilogno" ~ "zambilogno", 
      .default = FoodName_Recoded))
  
  if ("Name" %in% colnames(diet_df)) {
    
    diet_df <- diet_df %>%
      mutate(FoodName_Recoded = case_when(
        Name == "haricot, tsiasisa" & FoodName_Recoded == "" ~ "haricot",
        Name == "haricot, tsiasisa, voantsorako" & FoodName_Recoded == "" ~ "haricot",
        Name %in% c("vatsikopiky", "voatsikopoka", "vatsikobiky") & FoodName_Recoded == "" ~ "voatsikopoka",
        Name == "bolety lafariny" & FoodName_Recoded == "" ~ "baignet",
        Name == "moforavigny" & FoodName_Recoded == "" ~ "mofo ravina",
        Name == "pizina" & FoodName_Recoded == "" ~ "pizina",
        Name == "ranompary" & FoodName_Recoded == "" ~ "ranopary",
        Name == "siro" & FoodName_Recoded == "" ~ "siro",
        FoodName_Recoded == "vapaza" ~ "vapaza manta",
        Name == "vatsikopika" & FoodName_Recoded == "" ~ "voatsikopoka",
        .default = FoodName_Recoded))
  }
  return(diet_df)
}
```
  
```{r example-fix_recoded}
fix_recoded()
```
  
```{r tests-fix_recoded}
test_that("fix_recoded works", {
  expect_true(inherits(fix_recoded, "function")) 
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_cleaning_functions.Rmd", vignette_name = "Go further")
```

