graph LR
  style Legend fill:#FFFFFF00,stroke:#000000;
  style Graph fill:#FFFFFF00,stroke:#000000;
  subgraph Legend
    x2db1ec7a48f65a9b(["Outdated"]):::outdated
    xf1522833a4d242c5(["Up to date"]):::uptodate
    xeb2d7cac8a1ce544>"Function"]:::none
    xd03d7c7dd2ddda2b(["Regular target"]):::none
  end
  subgraph Graph
    direction LR
    x6f8c1d6470e24981(["fish_enc_g"]):::outdated --> x79100dac8b924b89(["dar_hh_fish_with_grams_no_weekly"]):::outdated
    x04ec71d6c69cf1a2(["hh_fish"]):::outdated --> x79100dac8b924b89(["dar_hh_fish_with_grams_no_weekly"]):::outdated
    x3f87a69e8b2529de(["mahery_files"]):::uptodate --> x79100dac8b924b89(["dar_hh_fish_with_grams_no_weekly"]):::outdated
    x3f87a69e8b2529de(["mahery_files"]):::uptodate --> x6f8c1d6470e24981(["fish_enc_g"]):::outdated
    xba950978057a8fde>"match_item"]:::uptodate --> xd2cc95bebb457d64>"fix_match"]:::uptodate
    x3f87a69e8b2529de(["mahery_files"]):::uptodate --> x04ec71d6c69cf1a2(["hh_fish"]):::outdated
    xd3a10a24e8b9f3f0(["target_files"]):::uptodate --> x3f87a69e8b2529de(["mahery_files"]):::uptodate
    xa166bcfc62def816>"unzip_tracked"]:::uptodate --> x3f87a69e8b2529de(["mahery_files"]):::uptodate
    xb6c98845f86dfafb>"register_inputs"]:::uptodate --> x7c66da3dee7f04e2(["repo_files"]):::uptodate
    xa052234f29b52a07>"fix_amount"]:::uptodate
    x2b898eaef57b0c62>"fix_fish"]:::uptodate
    xee0127aabbbec0f0>"fix_mah"]:::uptodate
    x2caa9ddba1672a42>"fix_makoba"]:::uptodate
    x019b3719a64bcbbe>"fix_med"]:::uptodate
    x44b32fb7c2028950>"fix_recoded"]:::uptodate
    x8fc1ffd4b2efc7e8>"fix_remove"]:::uptodate
    xab03c2a7b8b75fa1>"fix_trad_med"]:::uptodate
    x85067c2c1be27ab5>"fix_trans"]:::uptodate
    x7ab637c820b084b5>"fix_unit"]:::uptodate
    x77efecfe9969e520>"get_match"]:::uptodate
    xb84dcfc84cf938e5(["manifest"]):::uptodate
    xcdbe8bc09568c9ba>"merge_items"]:::uptodate
  end
  classDef outdated stroke:#000000,color:#000000,fill:#78B7C5;
  classDef uptodate stroke:#000000,color:#ffffff,fill:#354823;
  classDef none stroke:#000000,color:#000000,fill:#94a4ac;
