# WARNING - Generated by {fusen} from dev/flat_register_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("register_inputs lists only matching files from input zip", {
  tmpdir <- withr::local_tempdir()

  files <- file.path(
    tmpdir,
    c(
      "raw/MAHERY_clinic_2024.csv",
      "raw/MAHERY_households_2024.csv",
      "raw/OTHER_site_2024.csv",
      "metadata/readme.txt"
    )
  )

  dir.create(dirname(files[1]), recursive = TRUE)
  dir.create(dirname(files[4]), recursive = TRUE)
  file.create(files)

  zip_path <- file.path(tmpdir, "incoming_dataset.zip")
  old_wd <- setwd(tmpdir)
  withr::defer(setwd(old_wd))

  zip(
    zipfile = zip_path,
    files = c(
      "raw/MAHERY_clinic_2024.csv",
      "raw/MAHERY_households_2024.csv",
      "raw/OTHER_site_2024.csv",
      "metadata/readme.txt"
    )
  )

  result <- register_inputs(zip_path, regex = "MAHERY")

  expect_equal(
    sort(result),
    sort(c(
      "raw/MAHERY_clinic_2024.csv",
      "raw/MAHERY_households_2024.csv"
    ))
  )
})

test_that("unzip_tracked returns extracted file paths", {

  skip_if_not_installed("zip")

  tmpdir <- tempdir()

  file_a <- file.path(tmpdir, "a.txt")
  writeLines("hello", file_a)

  zipfile <- file.path(tmpdir, "test.zip")

  zip::zipr(
    zipfile = zipfile,
    files = file_a
  )

  extracted <- unzip_tracked(
    zipfile = zipfile,
    files = "a.txt",
    exdir = file.path(tmpdir, "out")
  )

  expect_true(all(file.exists(extracted)))
  expect_equal(basename(extracted), "a.txt")
})
