# WARNING - Generated by {fusen} from dev/flat_register_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("register_inputs works", {
  expect_true(inherits(register_inputs, "function"))
})
