#!/usr/bin/env bash
set -e

PROJECT_DIR=/n/holylabs/cgolden_lab/Lab/frontier/works/prospectors/prospectorMahery

cd "$PROJECT_DIR"

unset R_HOME R_LIBS R_LIBS_SITE
export R_ENVIRON_USER=/dev/null
export R_PROFILE_USER=/dev/null

export R_LIBS_USER="$PROJECT_DIR/.vscode/R/library/4.5"
mkdir -p "$R_LIBS_USER"

export PATH="$PROJECT_DIR/.spack-env/view/bin:$PATH"
export LD_LIBRARY_PATH="$PROJECT_DIR/.spack-env/view/lib:$PROJECT_DIR/.spack-env/view/lib64:$PROJECT_DIR/.spack-env/view/rlib/R/lib:${LD_LIBRARY_PATH:-}"

exec "$PROJECT_DIR/.spack-env/view/bin/R" "$@"