# WARNING - Generated by {fusen} from dev/flat_register_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' List matching file paths from a zip archive
#'
#' Lists the contents of a zipped dataset and returns the paths of files
#' whose names match the supplied regular expression.
#' 
#' @param input_path path to the zipped dataset
#' @param regex regular expression to filter the files to be registered
#' @importFrom dplyr filter pull
#' @importFrom stringr str_detect
#' @return vector of file paths
#' @export
#'
#' @examples
#' register_inputs(
#'   here(
#'     "data", 
#'     "inputs", 
#'     "01_gold_mine", 
#'     "madagascar-cohort-data-zip/madagascar_data_cleaning-main.zip"
#'     ),
#'   regex = "Data\\/MAHERY"
#'   )
register_inputs <- function(input_path, regex = "MAHERY") {
  
  # List the contents of the zip file
  contents <- unzip(input_path, list = TRUE)
  
  # Filter the contents based on the regex
  contents %>%
    filter(str_detect(Name, regex)) %>%
    pull(Name) %>%
    return()
  
}

#' Unzip selected files and return extracted paths
#'
#' Extracts matching files from a zip archive and returns the paths
#' of the extracted files for use in reproducible pipelines such as
#' `{targets}`.
#'
#' @param zipfile Path to zip archive.
#' @param files Character vector of internal zip paths to extract.
#' @param exdir Extraction directory.
#' @param junkpaths Should directory structure inside archive be discarded?
#' @param overwrite Should existing files be overwritten?
#'
#' @return Character vector of extracted file paths.
#'
#' @export
unzip_tracked <- function(
  zipfile,
  files,
  exdir,
  junkpaths = TRUE,
  overwrite = TRUE
) {

  info <- unzip(zipfile, list = TRUE)

  matched <- str_subset(info$Name, paste(files, collapse = "|"))

  out_files <- if (junkpaths) {
    file.path(exdir, basename(matched))
  } else {
    file.path(exdir, matched)
  }

  unzip(
    zipfile = zipfile,
    files = matched,
    exdir = exdir,
    junkpaths = junkpaths,
    overwrite = overwrite
  )

  out_files
}
