# WARNING - Generated by {fusen} from dev/flat_register_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' register_inputs Title
#'
#' Description of the function
#' 
#' @param input_path path to the zipped dataset
#' @param regex regular expression to filter the files to be registered
#' @importFrom dplyr filter pull
#' @importFrom stringr str_detect
#' @return vector of file paths
#' @export
#'
#' @examples
#' register_inputs(
#'   here(
#'     "data", 
#'     "inputs", 
#'     "01_gold_mine", 
#'     "madagascar-cohort-data-zip/madagascar_data_cleaning-main.zip"
#'     ),
#'   regex = "Data\\/MAHERY"
#'   )
register_inputs <- function(input_path, regex = "MAHERY") {
  
  # List the contents of the zip file
  contents <- unzip(input_path, list = TRUE)
  
  # Filter the contents based on the regex
  contents %>%
    filter(str_detect(Name, regex)) %>%
    pull(Name) %>%
    return()
  
}
